### ISSUE TITLE
documentation?

### ISSUE THREAD

**Issue by phillkOCCM** [TspringMSFT/PullAzureADSignInReports-#1]
hi, the readme indicates that there is a microsoft provided script at the following URL : https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/SignIns

however, it does not appear to have such. is this something that got depreciated?

**Comment by TspringMSFT** [comment]
That script did in fact get removed from the portal. So, it's good that the related code is available here still :)
