### ISSUE TITLE
Link from TechNet

### ISSUE THREAD

**Issue by dcbrown16** [TspringMSFT/PullAzureADSignInReports-#2]
Can you go back to the TechNet issue and just fix the link on the Description that points here? It's missing the trailing "-". 
https://gallery.technet.microsoft.com/scriptcenter/Pull-Azure-AD-Sign-In-3fead683

I found the correct link in the Q&A, but that would help people get here. Thanks!

**Comment by TspringMSFT** [comment]
I updated it. I am pretty sure I have before as well and TechNet reverted to an older version. Sadly that sort of thing happens with TechNet. Another reason to move to GitHub :)
