### ISSUE TITLE
does not contain a method named 'AcquireToken'

### ISSUE THREAD

**Issue by TheBigBear** [TspringMSFT/PullAzureADSignInReports-#3]
I am successfully connected to my MSOnline using Connect-MsolService and my tenant using connect-AzureAD but I still get only the following error and NO output from the script. 

```
Method invocation failed because
[Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext] does
not contain a method named 'AcquireToken'.
```

Import-Module Azure also works with no errors. What am I missing, how do I get this to give me an access token? I am using a global admin account and the same query I am trying to run in the script works just fine online in the browser at MS Graph Explorer beta.

**Comment by sailingbikeruk** [comment]
+1 here - same issue.

**Comment by TspringMSFT** [comment]
This script uses Active Directory Authentication Language (ADAL) libraries for authentication. ADAL must be installed via Azure PowerShell or the Azure SDK for authentication to work.

Can you make sure that you have the ADAL libraries from one of the above installs present and then retry?  This is a separate install in some PowerShell install versions.

**Comment by TheBigBear** [comment]
@TspringMSFT thanks. In my case it started working after I switched to using ```'AzureAD'``` module. I had stumbled across another article that mentioned that AzureAD is more up to date and can deal with MFA etc ... and voila it worked for me too. Might it be an idea to swap out the use of the 'older' module ```'Azure'``` in the script and put in ```'AzureAD'``` instead?
